add new smv functions
gosh-sh/gosh pull request #172
Opened 2022-11-01 21:48 UTC by SeHor05

2022-11-03 20:43 UTC, sauin requested changes

2022-11-03 20:43 UTC, sauin commented on contracts/gosh/repository.abi.json
> +			"name": "getContentAdress",
`getContentAdress` -> `getContentAddress`

2022-11-03 20:43 UTC, sauin commented on contracts/gosh/repository.sol
> +    function getContentAdress(string commit,
`getContentAdress` -> `getContentAddress`

2022-11-03 20:43 UTC, sauin commented on contracts/gosh/repository.sol
> +        string label) external view returns(address) {
reformat functions' signature, pls
```
function getContentAddress(string commit, string label)
    external view returns(address)
{
```

2022-11-04 09:32 UTC, rymkapro approved these changes

2022-11-04 09:58 UTC, andrew-kurochkin approved these changes

2022-11-04 09:59 UTC, merged