Changed traversion of the messages...
gosh-sh/gosh pull request #460
Opened 2023-04-25 08:04 UTC by sauin

… during blob restoration if snapshot was deleted

2023-04-25 08:26 UTC, SilkovAlexander commented on v1_x/git-remote-gosh/src/git_helper/fetch/mod.rs
> +                    branches.insert(branch.to_owned());
Isn't it the same as ^

2023-04-25 08:26 UTC, SilkovAlexander commented on v1_x/git-remote-gosh/src/git_helper/fetch/mod.rs
> +                branches.insert(onchain_commit.branch.clone());
->

2023-04-25 08:29 UTC, SilkovAlexander commented on v3_x/git-remote-gosh/src/blockchain/snapshot/load/diffs/iterator.rs
> +                tracing::trace!("snap={original_snapshot} is {}", if snapshot_is_active { "ACTIVE" } else { "NON_ACTIVE" });
v3 version of this file has more logs than others, I suggest add this extra tracing strings to at least the last version

2023-04-25 08:32 UTC, andrew-kurochkin requested changes
Please-please add comments to tests

2023-05-02 10:13 UTC, SilkovAlexander approved these changes, later dismissed

2023-05-02 11:04 UTC, andrew-kurochkin approved these changes

2023-05-02 11:05 UTC, merged