[onboarding] Create proposal for repo deploy if required
gosh-sh/gosh pull request #536
Opened 2023-08-15 11:08 UTC by sauin

2023-08-15 11:14 UTC, SilkovAlexander approved these changes, later dismissed

2023-08-17 08:40 UTC, SilkovAlexander requested changes

2023-08-17 08:40 UTC, SilkovAlexander commented on onboarding-workflow_v5/bin/gosh.sh
> +    tonos-cli -j -u network.gosh.sh run $1 getDetails {} \
Please move network and abi root to global variables

2023-08-17 08:40 UTC, SilkovAlexander commented on onboarding-workflow_v5/bin/find_proposal.sh
> +for account in $accounts; do
This loop checks accounts list once and exits. This logic can be wrong

2023-08-17 08:40 UTC, SilkovAlexander commented on onboarding-workflow_v5/bin/find_proposal.sh
> +done
mb add exit 1 after loop

2023-08-17 08:40 UTC, SilkovAlexander commented on onboarding-workflow_v5/src/eversdk/client.ts
> +                endpoints: ['network.gosh.sh']
Endpoint is passed via ENV VARIABLE take it from there

2023-08-17 08:40 UTC, SilkovAlexander commented on onboarding-workflow_v5/src/eversdk/dao.ts
> +    throw new Error(`Process "${args}" return code ${result.code}\n${stdout}`)
"returned"

2023-08-17 08:42 UTC, sauin commented on onboarding-workflow_v5/bin/find_proposal.sh
> +done
this return value processed too

2023-09-14 08:10 UTC, SilkovAlexander approved these changes

2023-09-14 08:11 UTC, merged